delete subset series schemas
statisticsnorway/gsim-raml-schema pull request #33
Opened 2020-12-15 08:31 UTC by drageset

Subsets have gotten their own repository, since they're not contributing to GSIM.

2020-12-16 08:45 UTC, runejo requested changes
There where also changes in https://github.com/statisticsnorway/gsim-raml-schema/pull/27 but i think we can leave them.

There is also an About.raml that needs to be updated on every PR.

2020-12-16 08:57 UTC, runejo commented
I aslo closed https://github.com/statisticsnorway/gsim-raml-schema/pull/29 since it was never merged

2020-12-16 09:03 UTC, runejo commented
Jeg la til dere på review @olbredes og @BjornRoarJoneid 
Saken er at vi i Klass uttrekk har flyttet våre schema til https://github.com/statisticsnorway/klass-subsets-schema for å bli ferdige. Denne PR er for rydde oppå i de endringene vi gjorde i dette gsim-raml-schema repo tidligere i år.

2020-12-16 09:16 UTC, olbredes requested changes
Husk å endre versjon og beskrivelse i About.raml også

2020-12-16 09:17 UTC, olbredes commented
Burde det sjekkes med @mmj-ssb  og @ohvssb at dette ikke brukes av LDS/metadata-gjengen i Dapla også ?

2020-12-16 09:26 UTC, mmj-ssb commented
Brukes ikke av Dapla

2020-12-16 10:44 UTC, olbredes approved these changes

2020-12-17 08:53 UTC, runejo approved these changes

2020-12-18 08:29 UTC, merged